<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="DESKTOP-82G9DU9" name="com.salesforce.testcases.TC001_LoginLogOut" tests="1" failures="0" timestamp="2023-04-02T12:14:19 IST" time="44.237" errors="1">
  <testcase name="runVerifyLogin" time="44.237" classname="com.salesforce.testcases.TC001_LoginLogOut">
    <error type="java.lang.RuntimeException">
      <![CDATA[java.lang.RuntimeException
at com.salesforce.selenium.api.base.SeleniumBase.locateElement(SeleniumBase.java:289)
at com.salesforce.pages.HomePage.verifyHomepage(HomePage.java:21)
at com.salesforce.testcases.TC001_LoginLogOut.runVerifyLogin(TC001_LoginLogOut.java:27)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- runVerifyLogin -->
  <system-out/>
</testsuite> <!-- com.salesforce.testcases.TC001_LoginLogOut -->
