<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-82G9DU9" ignored="0" name="Test" tests="1" failures="1" timestamp="2023-04-02T12:14:18 IST" time="44.993" errors="0">
  <testcase name="runVerifyLogin" time="39.777" classname="com.salesforce.testcases.TC001_LoginLogOut">
    <failure type="java.lang.RuntimeException">
      <![CDATA[java.lang.RuntimeException
at com.salesforce.selenium.api.base.SeleniumBase.locateElement(SeleniumBase.java:289)
at com.salesforce.pages.HomePage.verifyHomepage(HomePage.java:21)
at com.salesforce.testcases.TC001_LoginLogOut.runVerifyLogin(TC001_LoginLogOut.java:27)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- runVerifyLogin -->
</testsuite> <!-- Test -->
